### ISSUE TITLE
Empty test suite Error

### ISSUE THREAD

**Issue by jezinka** [lavong/SpockUnitTestsDemo#1]
Hi,

I cloned your project, open it in Android Studio. I tried to run tests from IDE but I got an error: 

Process finished with exit code 1
Class not found: "com.ingloriousmind.android.spockunittestsdemo.controller.ContactsProviderSpec"Empty test suite.

I don't know if it's an IDE Error or it's a bug in the settings

Best regards,
Paulina

**Comment by lavong** [comment]
Hello Paulina,

great that you are interested in testing with Spock. Your issue seems to be related to the Android Studio/IntelliJ IDEA, if you google it, you'll find plenty evidence. I saw it a couple of times in other projects as well. Should work after clean build. You might also want to try to run from command line. Just tried, works for me:

```
$ git clone git@github.com:lavong/SpockUnitTestsDemo.git
$ cd SpockUnitTestsDemo/
$ ./gradlew testDebug
...
BUILD SUCCESSFUL

Total time: 12.343 secs
$ 
```

HTH,
Lavong

**Comment by jezinka** [comment]
I already resolved this with a little help of my friends :) 

instead of this: 
apply plugin: 'groovyx.grooid.groovy-android'
should be this: 
apply plugin: 'groovyx.android'

and this
classpath 'org.codehaus.groovy:groovy-android-gradle-plugin:1.1.0'
instead of: 
classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.6'
